# Generated by Django 4.1.7 on 2023-04-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='payee_order_id',
            field=models.IntegerField(default=0),
        ),
    ]
