# Generated by Django 4.1.7 on 2023-04-25 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payApp', '0002_orderdetails_payee_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payApp.paymentmethoddetails'),
        ),
    ]
