# Generated by Django 4.1.7 on 2023-04-25 19:21

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payApp', '0004_alter_orderdetails_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentmethoddetails',
            name='card_number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethoddetails',
            name='cvv',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethoddetails',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
