# Generated by Django 4.1.7 on 2023-05-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payApp', '0005_itemdetails_item_price_orderdetails_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='item_type',
            field=models.CharField(default='TICKET', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='metadata',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='payee_item_id',
            field=models.IntegerField(default=0),
        ),
    ]
