# Generated by Django 4.1.7 on 2023-05-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payApp', '0006_itemdetails_item_type_itemdetails_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='payee_order_id',
            field=models.IntegerField(),
        ),
    ]
