# Generated by Django 4.1.7 on 2023-05-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payApp', '0008_remove_itemdetails_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethoddetails',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentmethoddetails',
            name='cvv',
            field=models.CharField(max_length=4),
        ),
    ]
